<a href="https://colab.research.google.com/github/EstherAbayomi07/S_tar/blob/main1/SECTION_30_data_mining_with_python_and_numpy(build_a_video_recommender_system).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#SECTION30 

In [2]:
import numpy

In [9]:
X = numpy.zeros((100, 5),
                dtype ="bool")

features = ["Investing101",
            "FunnyCatVideos",
            "BuraTech",
            "MammothInteracticve",
            "VideoGameReviewer"]

INVESTING101_INDEX   = 0
FUNNYCATVIDEOS_INDEX = 1
BURATECH_INDEX       = 2
MAMMOTHINTERACTIVE_INDEX = 3
VIDEOGAMEREVIEWER_INDEX = 4

VIEWERS_COUNT = X.shape[0]

LIKED_VIDEO = 1

for viewer in range(VIEWERS_COUNT):

  if numpy.random.random() < 0.3:

    X[viewer][INVESTING101_INDEX] = LIKED_VIDEO

    if numpy.random.random() < 0.5:

      X[viewer][FUNNYCATVIDEOS_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.2:

        X[viewer][BURATECH_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.3:

        X[viewer][MAMMOTHINTERACTIVE_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.4:

        X[viewer][VIDEOGAMEREVIEWER_INDEX] = LIKED_VIDEO
  
  else: 

      if numpy.random.random() < 0.5:

        X[viewer][FUNNYCATVIDEOS_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.3:

        X[viewer][BURATECH_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.2:

        X[viewer][MAMMOTHINTERACTIVE_INDEX] = LIKED_VIDEO

      if numpy.random.random() < 0.4:

        X[viewer][VIDEOGAMEREVIEWER_INDEX] = LIKED_VIDEO

      else:

        if numpy.random.random() < 0.7:

         X[viewer][BURATECH_INDEX] = LIKED_VIDEO

        if numpy.random.random() < 0.55:

         X[viewer][MAMMOTHINTERACTIVE_INDEX] = LIKED_VIDEO

        if numpy.random.random() < 0.8:

         X[viewer][VIDEOGAMEREVIEWER_INDEX] = LIKED_VIDEO  

  if X[viewer].sum() == 0:

    X[viewer][VIDEOGAMEREVIEWER_INDEX] = LIKED_VIDEO

numpy.savetxt("viewer_profiles.txt",
              X,
              fmt="%d") 

from google.colab import files

files.download("viewer_profiles.txt")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [10]:
X = numpy.loadtxt("viewer_profiles.txt")

print(X.shape)

(100, 5)


In [11]:
print(X[:5])

[[1. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0.]]


In [14]:
number_of_MammothInteractive_likes = 0

for viewer in X:

  if viewer[MAMMOTHINTERACTIVE_INDEX] == 1:

    number_of_MammothInteractive_likes += 1

print(number_of_MammothInteractive_likes)

40


In [15]:
rule_valid = 0

rule_invalid = 0


for viewer in X:

  if viewer[MAMMOTHINTERACTIVE_INDEX] == 1:

    if viewer[VIDEOGAMEREVIEWER_INDEX] == 1:

      rule_valid  += 1
    
    else:

      rule_invalid += 1

print("Rule: If a viewer liked Mammoth Interactive, they will like VideoGameReviewer")
print("{0} times the rule was valid".format(rule_valid))
print("{0} times the rule was invalid".format(rule_invalid))



Rule: If a viewer liked Mammoth Interactive, they will like VideoGameReviewer
33 times the rule was valid
7 times the rule was invalid


In [16]:
support = rule_valid 

confidence = rule_valid / number_of_MammothInteractive_likes

print("Support:  {0}".format(support))

print("Confidence: {0}".format(confidence))

Support:  33
Confidence: 0.825


In [17]:
print("Confidence: {0:.1f}%".format(100 * confidence))

Confidence: 82.5%


In [21]:
number_of_samples, number_of_features = X.shape

from collections import defaultdict

number_of_occurences = defaultdict(int)

times_rule_valid = defaultdict(int)

times_rule_invalid = defaultdict(int)

for viewer in X:

  for premise in range(number_of_features):

    if viewer[premise] == 0: continue

    number_of_occurences[premise] += 1

    for conclusion in range(number_of_features):

      if premise ==conclusion:

        continue

      if viewer[conclusion] == 1:

        times_rule_valid[(premise, conclusion)] += 1

      else:

        times_rule_invalid[(premise, conclusion)] += 1

support = times_rule_valid

confidence = defaultdict(float)

for premise, conclusion in times_rule_valid.keys():

  confidence[(premise, conclusion)] = times_rule_valid[(premise, conclusion)] / number_of_occurences[premise]

for premise, conclusion in confidence:

  first_channel = features[premise]

  second_channel = features[conclusion]

  print("Rule: If a viewer {0}, they will also like {1}".format(first_channel,
                                                                second_channel))
  
  print("Confidence: {0:.1f}%".format( 100 * confidence[(premise, conclusion)]))

  print("Support: {0}".format(support[(premise, conclusion)]))

  print(" ")



Rule: If a viewer Investing101, they will also like FunnyCatVideos
Confidence: 40.6%
Support: 13
 
Rule: If a viewer Investing101, they will also like MammothInteracticve
Confidence: 9.4%
Support: 3
 
Rule: If a viewer Investing101, they will also like VideoGameReviewer
Confidence: 15.6%
Support: 5
 
Rule: If a viewer FunnyCatVideos, they will also like Investing101
Confidence: 28.3%
Support: 13
 
Rule: If a viewer FunnyCatVideos, they will also like MammothInteracticve
Confidence: 45.7%
Support: 21
 
Rule: If a viewer FunnyCatVideos, they will also like VideoGameReviewer
Confidence: 78.3%
Support: 36
 
Rule: If a viewer MammothInteracticve, they will also like Investing101
Confidence: 7.5%
Support: 3
 
Rule: If a viewer MammothInteracticve, they will also like FunnyCatVideos
Confidence: 52.5%
Support: 21
 
Rule: If a viewer MammothInteracticve, they will also like VideoGameReviewer
Confidence: 82.5%
Support: 33
 
Rule: If a viewer VideoGameReviewer, they will also like Investing101
Co

In [22]:
from pprint import pprint

pprint(list(support.items()))

[((0, 1), 13),
 ((0, 3), 3),
 ((0, 4), 5),
 ((1, 0), 13),
 ((1, 3), 21),
 ((1, 4), 36),
 ((3, 0), 3),
 ((3, 1), 21),
 ((3, 4), 33),
 ((4, 0), 5),
 ((4, 1), 36),
 ((4, 3), 33),
 ((2, 3), 24),
 ((3, 2), 24),
 ((0, 2), 1),
 ((1, 2), 19),
 ((2, 0), 1),
 ((2, 1), 19),
 ((2, 4), 34),
 ((4, 2), 34)]


In [23]:
from operator import itemgetter

support_sorted = sorted(support.items(),
                        key = itemgetter(1),
                        reverse=True)

def print_results(premise, conclusion, support, confidence, features):

  first_channel = features[premise]

  second_channel = features[conclusion]

  print("Rule: If a viewer liked {0}, they will also like {1}".format(first_channel,
                                                                      second_channel))
  
  print("Confidence: {0:.1f}%".format( 100 * confidence[(premise, conclusion)]))

  print("Support: {0}".format(support[(premise, conclusion)]))

  print(" ")

for index in range(5):

  (premise, conclusion) = support_sorted[index][0]

  print_results(premise, conclusion, support, confidence, features)

Rule: If a viewer liked FunnyCatVideos, they will also like VideoGameReviewer
Confidence: 78.3%
Support: 36
 
Rule: If a viewer liked VideoGameReviewer, they will also like FunnyCatVideos
Confidence: 53.7%
Support: 36
 
Rule: If a viewer liked BuraTech, they will also like VideoGameReviewer
Confidence: 85.0%
Support: 34
 
Rule: If a viewer liked VideoGameReviewer, they will also like BuraTech
Confidence: 50.7%
Support: 34
 
Rule: If a viewer liked MammothInteracticve, they will also like VideoGameReviewer
Confidence: 82.5%
Support: 33
 


In [24]:
confidence_sorted = sorted(confidence.items(),
                           key = itemgetter(1),
                           reverse = True)

for index in range(5):

  (premise, conclusion) = confidence_sorted[index][0]

  print_results(premise, conclusion, support, confidence, features)

Rule: If a viewer liked BuraTech, they will also like VideoGameReviewer
Confidence: 85.0%
Support: 34
 
Rule: If a viewer liked MammothInteracticve, they will also like VideoGameReviewer
Confidence: 82.5%
Support: 33
 
Rule: If a viewer liked FunnyCatVideos, they will also like VideoGameReviewer
Confidence: 78.3%
Support: 36
 
Rule: If a viewer liked BuraTech, they will also like MammothInteracticve
Confidence: 60.0%
Support: 24
 
Rule: If a viewer liked MammothInteracticve, they will also like BuraTech
Confidence: 60.0%
Support: 24
 
